"""add user_id to agents

Revision ID: 0b4251279fdf
Revises: 0b4c6543c137
Create Date: 2026-03-02 10:41:27.637782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4251279fdf'
down_revision: Union[str, Sequence[str], None] = '0b4c6543c137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'agents', ['user_id'])
    op.create_foreign_key(None, 'agents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='unique')
    op.drop_column('agents', 'user_id')
    # ### end Alembic commands ###
