"""adding unique constraint on property field of deals

Revision ID: 0b4c6543c137
Revises: de970959728b
Create Date: 2026-02-21 19:56:31.572481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4c6543c137'
down_revision: Union[str, Sequence[str], None] = 'de970959728b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'deals', ['property_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='unique')
    # ### end Alembic commands ###
