"""unique constraint buyer property interest

Revision ID: 1a1b0d87ee97
Revises: 0b4251279fdf
Create Date: 2026-03-02 11:15:12.323532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1b0d87ee97'
down_revision: Union[str, Sequence[str], None] = '0b4251279fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_buyer_property', 'interests', ['buyer_id', 'property_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_buyer_property', 'interests', type_='unique')
    op.alter_column('agents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
