"""adding verification_status and remarks field

Revision ID: 357c62fbbc40
Revises: e2966aa22b88
Create Date: 2026-03-03 16:27:13.694376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357c62fbbc40'
down_revision: Union[str, Sequence[str], None] = 'e2966aa22b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('remarks', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('verification_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'verification_status')
    op.drop_column('properties', 'remarks')
    # ### end Alembic commands ###
