"""add verification fields to properties

Revision ID: 40f2b91517a5
Revises: 53be5459996a
Create Date: 2026-03-02 11:41:49.118944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f2b91517a5'
down_revision: Union[str, Sequence[str], None] = '53be5459996a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('verified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'properties', 'agents', ['verified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_column('properties', 'verified_by')
    op.drop_column('properties', 'is_verified')
    # ### end Alembic commands ###
