"""changing verfied by firls name to agent

Revision ID: 453f2dc4c0a0
Revises: 8c3e38192f39
Create Date: 2026-03-02 19:47:00.018811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453f2dc4c0a0'
down_revision: Union[str, Sequence[str], None] = '8c3e38192f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('agent', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('properties_verified_by_fkey'), 'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'agents', ['agent'], ['id'])
    op.drop_column('properties', 'verified_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_foreign_key(op.f('properties_verified_by_fkey'), 'properties', 'agents', ['verified_by'], ['id'])
    op.drop_column('properties', 'agent')
    # ### end Alembic commands ###
