"""enum for purpose and property type

Revision ID: 5a3394cd1c14
Revises: 0f359b797ee1
Create Date: 2026-03-02 13:19:17.958426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3394cd1c14'
down_revision: Union[str, Sequence[str], None] = '0f359b797ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum types first
    propertypurpose = sa.Enum('buy', 'rent', name='propertypurpose')
    propertytype = sa.Enum('apartment', 'house', 'flat','plot', 'commercial', name='propertytype')
    propertypurpose.create(op.get_bind())
    propertytype.create(op.get_bind())

    # Then alter the columns
    op.alter_column('properties', 'purpose',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum('buy', 'rent', name='propertypurpose'),
        existing_nullable=False,
        postgresql_using='purpose::propertypurpose'
    )
    op.alter_column('properties', 'property_type',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum('apartment', 'house', 'plot', 'flat','commercial', name='propertytype'),
        existing_nullable=False,
        postgresql_using='property_type::propertytype'
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'property_type',
               existing_type=sa.Enum('apartment', 'house', 'plot','flat', 'commercial', name='propertytype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('properties', 'purpose',
               existing_type=sa.Enum('buy', 'rent', name='propertypurpose'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
