"""add counter amount and status to interests

Revision ID: 7af169f3c410
Revises: 71237772b44c
Create Date: 2026-01-28 19:20:59.997831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af169f3c410'
down_revision: Union[str, Sequence[str], None] = '71237772b44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interests', sa.Column('counter_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interests', 'counter_amount')
    # ### end Alembic commands ###
