"""add city to agent table and location in property

Revision ID: 8c3e38192f39
Revises: 922a893e18f6
Create Date: 2026-03-02 14:21:36.462707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3e38192f39'
down_revision: Union[str, Sequence[str], None] = '922a893e18f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'city')
    # ### end Alembic commands ###
