"""add location table

Revision ID: 922a893e18f6
Revises: 5a3394cd1c14
Create Date: 2026-03-02 13:59:30.682929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922a893e18f6'
down_revision: Union[str, Sequence[str], None] = '5a3394cd1c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('location_id', sa.Integer(), nullable=True))
    op.alter_column('properties', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'properties', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.alter_column('properties', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('properties', 'location_id')
    # ### end Alembic commands ###
