"""add bedrooms bathrooms area to properties

Revision ID: 99bbd1de86fa
Revises: 357c62fbbc40
Create Date: 2026-06-07 20:53:47.056199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99bbd1de86fa'
down_revision: Union[str, Sequence[str], None] = '357c62fbbc40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal_documents', sa.Column('reupload_deadline', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('properties', sa.Column('bedrooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('bathrooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('area', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'area')
    op.drop_column('properties', 'bathrooms')
    op.drop_column('properties', 'bedrooms')
    op.drop_column('deal_documents', 'reupload_deadline')
    # ### end Alembic commands ###
