"""add unique constraint on interestid in deal table

Revision ID: de970959728b
Revises: 4a27102dbde1
Create Date: 2026-01-30 00:07:49.951972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de970959728b'
down_revision: Union[str, Sequence[str], None] = '4a27102dbde1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_deals_interest_id", 'deals', ['interest_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_deals_interest_id", 'deals', type_='unique')
    # ### end Alembic commands ###
