"""ALTER TABLE properties ADD COLUMN verification_deadline TIMESTAMPTZ

Revision ID: e2966aa22b88
Revises: 453f2dc4c0a0
Create Date: 2026-03-03 15:37:03.032322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2966aa22b88'
down_revision: Union[str, Sequence[str], None] = '453f2dc4c0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('verification_deadline', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('properties', sa.Column('is_modified', sa.Boolean(), nullable=True))
    op.drop_column('properties', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('properties', 'is_modified')
    op.drop_column('properties', 'verification_deadline')
    # ### end Alembic commands ###
